apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 10m
  chart:
    spec:
      chart: mongodb
      version: "16.5.27"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    architecture: standalone
    replicaCount: 1
    auth:
      existingSecret: mongodb-auth
      usernames:
        - unifi
        - unifi
        - unifi
      databases:
        - unifi
        - unifi_stat
        - unifi_audit
    persistence:
      enabled: true
      existingClaim: mongodb-static-pvc
    resources:
      requests:
        cpu: 400m
        memory: 640Mi
      limits:
        cpu: 800m
        memory: 1.2Gi
    tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300