apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-static-pvc
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: mongodb-static-pv
  storageClassName: ""