apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: db
  namespace: flux-system
spec:
  interval: 5m
  path: cluster/redcloud/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-infra