apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/redcloud/infra/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-infra
  dependsOn:
    - name: metallb-base