apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-base
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/redcloud/infra/metallb/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-infra