apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-resources
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/redcloud/infra/traefik/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-infra
  dependsOn:
    - name: traefik-base