apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  path: cluster/redcloud/infra/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-infra