apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-resources
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/redcloud/infra/cert-manager/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: pve-infra
  dependsOn:
    - name: cert-manager-base