apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openspeedtest
  - mailrise
  - unifi-network-application
  - uptime-kuma
  - immich
  - nextcloud
  - router
  - bt-switch
  - modem
  - pihole
  - nutweb