apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    sources:
      - ingress
      - service
      - traefik-proxy
    extraArgs:
      - --traefik-disable-legacy
      - --source=traefik-proxy
    logLevel: error
    logFormat: json
    interval: 5m
    provider: 
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
          tag: latest
          pullPolicy: IfNotPresent
        env:
          - name: LOG_FORMAT
            value: json
          - name: LOG_LEVEL
            value: error
          - name: MIKROTIK_DEFAULT_TTL
            value: "3600"
          - name: MIKROTIK_DEFAULT_COMMENT
            value: Managed by ExternalDNS
          - name: MIKROTIK_BASEURL
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: MIKROTIK_BASEURL
          - name: MIKROTIK_USERNAME
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: MIKROTIK_USERNAME
          - name: MIKROTIK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: MIKROTIK_PASSWORD
          - name: MIKROTIK_SKIP_TLS_VERIFY
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: MIKROTIK_SKIP_TLS_VERIFY
          - name: DOMAIN_FILTER
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: DOMAIN_FILTER
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5