apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: uptime-kuma-pv
  namespace: kube-system
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-pv
spec:
  storageClassName: uptime-kuma-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/share/k8s/uptime-kuma-pv
    server: 10.0.4.10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pv-claim
  namespace: uptime-kuma
spec:
  storageClassName: uptime-kuma-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
