apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-cert
  namespace: router
spec:
  secretName: router-mesh-rigsb-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: router.mesh.rigsb.net
  dnsNames:
    - router.mesh.rigsb.net