apiVersion: batch/v1
kind: Job
metadata:
  name: nextcloud-initdb
  namespace: nextcloud
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: initdb
          image: postgres:14
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db
                  key: db-password
          command: ["sh", "-c"]
          args:
            - |
              psql -h postgresql.postgresql.svc.cluster.local -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'nextcloud'" | grep -q 1 || \
              psql -h postgresql.postgresql.svc.cluster.local -U postgres -c "CREATE DATABASE nextcloud"