apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-static-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.4.10
    path: /mnt/share/k8s/nextcloud-pv
  persistentVolumeReclaimPolicy: Retain