apiVersion: batch/v1
kind: CronJob
metadata:
  name: unifi-backup
  namespace: unifi-network-application
  labels:
    app: unifi-backup
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: gitea-registry
          containers:
          - name: unifi-backup
            image: gitea.mesh.rigsb.net/eric/backup-runner:latest
            env:
            - name: RESTIC_CACHE_DIR
              value: "/tmp"
            - name: RESTIC_PASSWORD_FILE
              value: "/etc/restic-secret/password"
            command:
            - /bin/bash
            - -c
            - |
              source /scripts/backup-service.sh
              backup_service "UniFi" "/backup/k8s-unifi" "/data/data/backup"
            volumeMounts:
            - name: unifi-data
              mountPath: /data
              readOnly: true
            - name: restic-secret
              mountPath: /etc/restic-secret
              readOnly: true
            - name: backup-storage
              mountPath: /backup
            - name: backup-scripts
              mountPath: /scripts
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
          serviceAccountName: unifi-backup-sa
          volumes:
          - name: unifi-data
            persistentVolumeClaim:
              claimName: unifi-config-pvc
          - name: restic-secret
            secret:
              secretName: restic-secret
          - name: backup-storage
            nfs:
              server: 10.0.4.8
              path: /mnt/backup
          - name: backup-scripts
            configMap:
              name: backup-scripts
              defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unifi-backup-sa
  namespace: unifi-network-application
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-secrets-reader
  namespace: unifi-network-application
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: unifi-backup-secrets-binding
  namespace: unifi-network-application
subjects:
- kind: ServiceAccount
  name: unifi-backup-sa
  namespace: unifi-network-application
roleRef:
  kind: Role
  name: backup-secrets-reader
  apiGroup: rbac.authorization.k8s.io
