apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-network-application
  namespace: unifi-network-application
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: unifi-network-application
  template:
    metadata:
      labels:
        app: unifi-network-application
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      initContainers:
        - name: fix-perms
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 1000:1000 /config"]
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: unifi
          image: lscr.io/linuxserver/unifi-network-application:9.4.19-ls104
          env:
            - name: MONGO_HOST
              value: mongodb.mongodb.svc.cluster.local
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: "unifi"
            - name: MONGO_AUTHSOURCE
              value: "admin"
            - name: MONGO_USER
              value: "unifi"
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: unifi-db-secret
                  key: password
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MEM_LIMIT
              value: "2048"
            - name: MEM_STARTUP
              value: "1024"
          ports:
            - containerPort: 8443
          resources:
            requests:
              cpu: 400m
              memory: 640Mi
            limits:
              cpu: 800m
              memory: 1.2Gi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: unifi-config-pvc