apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grant-unifi-roles.yaml
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - ingress-tcp-udp.yaml
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - backup-job.yaml
  - servers-transport.yaml
  - service.yaml
  - pdb.yaml