apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
  nfs:
    path: /mnt/share/k8s/unifi-config-pv
    server: 10.0.4.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-backup-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
  nfs:
    server: 10.0.4.8
    path: /mnt/backup
  persistentVolumeReclaimPolicy: Retain