apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresql-pv
  namespace: kube-system
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  storageClassName: postgresql-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/share/k8s/postgresql-pv
    server: 10.0.4.10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  namespace: postgresql
spec:
  storageClassName: postgresql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
