apiVersion: batch/v1
kind: CronJob
metadata:
  name: immich-backup
  namespace: immich
  labels:
    app: immich-backup
spec:
  schedule: "45 6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: gitea-registry
          containers:
          - name: immich-backup
            image: gitea.mesh.rigsb.net/eric/backup-runner:latest
            env:
            - name: RESTIC_CACHE_DIR
              value: "/tmp"
            - name: RESTIC_PASSWORD_FILE
              value: "/etc/restic-secret/password"
            command:
            - /bin/bash
            - -c
            - |
              source /scripts/backup-service.sh
              backup_service "Immich" "/backup/k8s-immich" "/usr/src/app /cache"
            volumeMounts:
            - name: immich-library
              mountPath: /usr/src/app
              readOnly: true
            - name: immich-cache
              mountPath: /cache
              readOnly: true
            - name: restic-secret
              mountPath: /etc/restic-secret
              readOnly: true
            - name: backup-storage
              mountPath: /backup
            - name: backup-scripts
              mountPath: /scripts
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 300m
                memory: 512Mi
          serviceAccountName: immich-backup-sa
          volumes:
          - name: immich-library
            persistentVolumeClaim:
              claimName: immich-library-pvc
          - name: immich-cache
            persistentVolumeClaim:
              claimName: immich-ml-cache-pvc
          - name: restic-secret
            secret:
              secretName: restic-secret
          - name: backup-storage
            nfs:
              server: 10.0.4.8
              path: /mnt/backup
          - name: backup-scripts
            configMap:
              name: backup-scripts
              defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-backup-sa
  namespace: immich
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-secrets-reader
  namespace: immich
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: immich-backup-secrets-binding
  namespace: immich
subjects:
- kind: ServiceAccount
  name: immich-backup-sa
  namespace: immich
roleRef:
  kind: Role
  name: backup-secrets-reader
  apiGroup: rbac.authorization.k8s.io
