apiVersion: v1
kind: PersistentVolume
metadata:
  name: ext-lib-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.4.10
    path: /mnt/share/osxphotos
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ext-lib-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: ext-lib-pv
  storageClassName: ""