apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: immich-server-pdb
  namespace: immich
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: immich-machine-learning-pdb
  namespace: immich
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: machine-learning
      app.kubernetes.io/instance: immich
