apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/share/k8s/immich-library-pv
    server: 10.0.4.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ml-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/share/k8s/immich-machine-learning-cache-pv
    server: 10.0.4.10
  persistentVolumeReclaimPolicy: Retain