apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - traefik-values.yaml
  - helmrelease.yaml
  - pdb.yaml

patches:
  - path: traefik-service-patch.yaml
    target:
      kind: Service
      name: traefik
      namespace: traefik