apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: "21.2.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    architecture: standalone
    replicaCount: 1
    auth:
      existingSecret: redis-auth
    master:
      persistence:
        enabled: true
        existingClaim: redis-static-pvc
      resources:
        requests:
          cpu: 200m
          memory: 384Mi
        limits:
          cpu: 400m
          memory: 768Mi