apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-static-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: redis-static-pv
  storageClassName: ""